title: riot labs
description: Blogging about tech, embedded, open source, life
meta_description: "meta description"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: /
domain_name: 'https://blog.riot-labs.de'
google_analytics: 'UA-XXXXXXXX-X'
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url:            'https://blog.riot-labs.de'
author:         'Your Name'

timezone: Europe/Berlin
